version: '3'

services:
  postgis:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_DB: farm2u_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_PORT: 5432
    ports:
      - "5433:5432"
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
      - ./data/sql:/docker-entrypoint-initdb.d

